apiVersion: apps/v1
kind: Deployment
metadata:
  name: too-complicated
spec:
  replicas: 1
  selector:
    matchLabels:
      app: too-complicated
  template:
    metadata:
      labels:
        app: too-complicated
    spec:
      containers:
      - name: too-complicated
        image: asia-northeast1-docker.pkg.dev/furudono/too-complicated/app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
