baseURL: https://blog.nfurudono.com
languageCode: ja-jp
defaultContentLanguage: ja
languages:
  en:
    languageName: English
    weight: 10
    title: hello
  ja:
    languageName: Japanese
title: ツイートするには長すぎる
copyright: '&copy;{currentYear} Naoya Furudono'
enableRobotsTXT: true
googleAnalytics: G-ES42FPF4D5
enableGitInfo: true
hasCJKLanguage: true
taxonomies:
  tag: tags
author:
  name: Naoya Furudono
frontmatter:
  date:
    - :filename
    - :default
  lastmod:
    - lastmod
    - updated
    - :git
Params:
  twitter: https://twitter.com/furudono2
  instagram: https://www.instagram.com/donofuru/
  github: https://github.com/naoyafurudono
  linkedin: https://www.linkedin.com/in/naoya-furudono
  showReadMore: false
  mainSections:
    - posts
    # - daily 
  images:
    - images/thumbnail.png
  listPageDateFormat: 2006-01-02 MST
  singlePageDateFormat: 2006-01-02 MST
markup:
  goldmark:
    renderer:
      # to render iframe
      unsafe: true
    extensions:
      cjk:
        enable: true
        eastAsianLineBreaks: true
  highlight:
    codeFences: false
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    tabWidth: 2
    menu:
      - main
      - footer
menu:
  main:
    - identifier: whoiam
      name: Profile
      url: /profile/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: about
      url: /about/
      weight: 3
