# 参考
# https://github.com/kimcc/hugo-theme-noteworthy/blob/master/exampleSite/config.toml

baseURL = 'https://naoyafurudono.github.io'
languageCode = 'ja-jp'
title = "Furudono's blog"
theme = 'noteworthy'
copyright = "&copy;{currentYear} Naoya Furudono"

enableRobotsTXT = true
googleAnalytics = "G-ES42FPF4D5"

enableGitInfo = true
hasCJKLanguage = true

[taxonomies]
  tag = "tags"

[author]
  name = "Naoya Furudono"

[frontmatter]
  date = [':filename', ':default']
  lastmod = ["lastmod", "updated", ":git"]

[Params]
  description = "Personal blog"
  twitter = "https://twitter.com/furudono2"
  github = "https://github.com/naoyafurudono"
  linkedin = "https://www.linkedin.com/in/naoya-furudono"
  showReadMore = false
  mainSections = ['posts', 'daily']

[markup]
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    # style = "algol_nu"
    tabWidth = 2

menu = ['main', 'footer']

[[menu.main]]
    identifier = "whoiam"
    name = "Who I am"
    url = "/portfolio/bio"
    weight = 1

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
