baseURL = 'https://naoyafurudono.github.io'
languageCode = 'ja-jp'
title = 'nfurudono'
theme = 'noteworthy'

googleAnalytics = "G-ES42FPF4D5"

enableGitInfo = true
hasCJKLanguage = true

[Params]
twitter = "https://twitter.com/furudono2"

