baseURL = 'https://naoyafurudono.github.io'
languageCode = 'ja-jp'
title = 'nfurudono'
theme = 'noteworthy'

googleAnalytics = "G-ES42FPF4D5"

enableGitInfo = true
hasCJKLanguage = true

[Params]
twitter = "https://twitter.com/furudono2"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "algol_nu"
    tabWidth = 2
