#!/bin/bash

if [ $# -ne 0 ]; then
  name="daily/$1"
else
  name="daily/$(date "+%Y-%m-%d")"
fi
path="content/${name}.md"
if [[ -f $path ]]; then
  nvim "$path"
else
  hugo new "${name}.md" && nvim "$path"
fi
