services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  front:
    build: frontend
    ports:
      - "3000:3000"
  backend:
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
