// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetFile implements getFile operation.
//
// Get a file by filename.
//
// GET /files/{filename}
func (UnimplementedHandler) GetFile(ctx context.Context, params GetFileParams) (r GetFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Health implements health operation.
//
// Health check endpoint.
//
// GET /health
func (UnimplementedHandler) Health(ctx context.Context) (r *HealthOK, _ error) {
	return r, ht.ErrNotImplemented
}
