// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetFile implements getFile operation.
	//
	// Get a file by filename.
	//
	// GET /files/{filename}
	GetFile(ctx context.Context, params GetFileParams) (GetFileRes, error)
	// Health implements health operation.
	//
	// Health check endpoint.
	//
	// GET /health
	Health(ctx context.Context) (*HealthOK, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
