// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	ht "github.com/ogen-go/ogen/http"
)

func encodeUploadFileRequest(
	req UploadFileReq,
	r *http.Request,
) error {
	const contentType = "application/octet-stream"
	body := req
	ht.SetBody(r, body, contentType)
	return nil
}
