name: GitHub Pages Deployment
permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
      
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@3a287949d38134f0920e6ac20032acef6d4a23c4
        with:
          hugo-version: latest
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@ababa3d330af34b07419f6bc9f4a6b817ed7930b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: blog.nfurudono.com
      - name: Notify
        uses: sarisia/actions-status-discord@ac3f7e25a1804993b2569b1e87daecb58f68d7c5
        if: ${{ success() || failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          url: https://blog.nfurudono.com
