name: GitHub Pages Deployment

on:
  push:
    branches:
      - main
        # paths-ignore:
        #   - '**'  # すべてのパスを無視するデフォルトの設定

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: startsWith(github.event.commits[0].message, 'deploy')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: blog.nfurudono.com
      - name: Notify
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() || failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          url: https://blog.nfurudono.com
